In [1]:
import glob
import json
import torch
import flash_attn
import pandas as pd
from tqdm.notebook import tqdm
from datasets import load_dataset
from transformers import AutoTokenizer, AutoModelForSequenceClassification
from sklearn.metrics import accuracy_score, classification_report, \
                            roc_auc_score, confusion_matrix

model_used = '474M'

In [2]:
# load reranker model
tokenizer = AutoTokenizer.from_pretrained("mesolitica/reranker-malaysian-mistral-474M-32k")
reranker_model = AutoModelForSequenceClassification.from_pretrained(
    "mesolitica/reranker-malaysian-mistral-474M-32k",
    use_flash_attention_2 = True,
    torch_dtype = torch.bfloat16,
    use_cache = False
)

config.json:   0%|          | 0.00/747 [00:00<?, ?B/s]

model.safetensors:   0%|          | 0.00/884M [00:00<?, ?B/s]

The model was loaded with use_flash_attention_2=True, which is deprecated and may be removed in a future release. Please use `attn_implementation="flash_attention_2"` instead.
You are attempting to use Flash Attention 2.0 with a model not initialized on GPU. Make sure to move the model to GPU after initializing it on CPU with `model.to('cuda')`.


In [3]:
# push model to the GPU!
_ = reranker_model.cuda().eval()

In [5]:
!nvidia-smi

Fri Apr 26 15:47:06 2024       
+---------------------------------------------------------------------------------------+
| NVIDIA-SMI 535.54.03              Driver Version: 535.54.03    CUDA Version: 12.2     |
|-----------------------------------------+----------------------+----------------------+
| GPU  Name                 Persistence-M | Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |         Memory-Usage | GPU-Util  Compute M. |
|                                         |                      |               MIG M. |
|=========================================+======================+======================|
|   0  NVIDIA A100 80GB PCIe          On  | 00000001:00:00.0 Off |                    0 |
| N/A   38C    P0              68W / 300W |   6767MiB / 81920MiB |      0%      Default |
|                                         |                      |             Disabled |
+-----------------------------------------+----------------------+--

### Inference & Evaluation

#### 1.0 Common Crawl QA

In [6]:
f = "test_datasets/test-reformatted-common-crawl-qa.jsonl"
f_name = f.split('reformatted-')[-1].split('.')[0]

test_dataset = pd.read_json(f, lines=True)
test_dataset['dataset_source'] = f_name

print('Shape:', test_dataset.shape)
test_dataset.head(3)

Shape: (20949, 5)


query  \
0  Bagaimana cara penghantaran dan kos penghantar...   
1  Apakah jenama bateri kereta yang disediakan ol...   
2  Apakah kawasan liputan untuk servis hantar bat...   

                                                text  label split  \
0  Ladam merupakan barang buatan yang lazimnya di...      0  test   
1  Komik adalah sejenis seni visual yang menggabu...      0  test   
2  untuk memecat Lawton, meninggalkan sekali lagi...      0  test   

    dataset_source  
0  common-crawl-qa  
1  common-crawl-qa  
2  common-crawl-qa

In [7]:
# initialize a list to store all the scores
scores = []
batch_size = 10

for n in tqdm(range(0, len(test_dataset), batch_size)):
    batch = []
    with torch.no_grad():
        for q, t in zip(test_dataset['query'][n: n + batch_size], test_dataset['text'][n: n + batch_size]):
            input_ids = tokenizer.encode_plus(q, t)
            input_ids.pop('token_type_ids')
            batch.append(input_ids)
        padded = tokenizer.pad(batch, return_tensors = 'pt').to('cuda')
        scores.extend(reranker_model(**padded).logits.cpu().detach().float().numpy().argmax(axis = 1).tolist())

  0%|          | 0/2095 [00:00<?, ?it/s]

You're using a PreTrainedTokenizerFast tokenizer. Please note that with a fast tokenizer, using the `__call__` method is faster than using a method to encode the text followed by a call to the `pad` method to get a padded encoding.


In [8]:
# Evaluate predictions (macro)
true_labels = test_dataset["label"]
accuracy = accuracy_score(true_labels, scores)
roc_auc = roc_auc_score(true_labels, scores)
print("Accuracy:", accuracy)
print("ROC-AUC:", roc_auc)
print("\nClassification Report:")
print(classification_report(
    true_labels,
    scores,
    target_names=["class 0", "class 1"],
    digits=5
))
print("\nConfusion Matrix:")
print(confusion_matrix(true_labels, scores))

Accuracy: 0.9947968876796028
ROC-AUC: 0.9947968717173516

Classification Report:
              precision    recall  f1-score   support

     class 0    0.99447   0.99513   0.99480     10475
     class 1    0.99513   0.99446   0.99479     10474

    accuracy                        0.99480     20949
   macro avg    0.99480   0.99480   0.99480     20949
weighted avg    0.99480   0.99480   0.99480     20949


Confusion Matrix:
[[10424    51]
 [   58 10416]]


In [9]:
# save and export inferenced dataframe
inferenced_df = pd.concat([test_dataset, pd.DataFrame(scores, columns=['predicted_label'])], axis=1)
inferenced_df.head(3)

query  \
0  Bagaimana cara penghantaran dan kos penghantar...   
1  Apakah jenama bateri kereta yang disediakan ol...   
2  Apakah kawasan liputan untuk servis hantar bat...   

                                                text  label split  \
0  Ladam merupakan barang buatan yang lazimnya di...      0  test   
1  Komik adalah sejenis seni visual yang menggabu...      0  test   
2  untuk memecat Lawton, meninggalkan sekali lagi...      0  test   

    dataset_source  predicted_label  
0  common-crawl-qa                0  
1  common-crawl-qa                0  
2  common-crawl-qa                0

In [10]:
inferenced_df.to_json(
    f'inferenced_output/{model_used}-inferenced-{f_name}.jsonl',
    orient='records',
    lines=True
)

#### 2.0 Facebook

In [11]:
f = "test_datasets/test-reformatted-facebook.jsonl"
f_name = f.split('reformatted-')[-1].split('.')[0]

test_dataset = pd.read_json(f, lines=True)
test_dataset['dataset_source'] = f_name

print('Shape:', test_dataset.shape)
test_dataset.head(3)

Shape: (45000, 5)


query  \
0                         Sekapur sirih road dah   
1  Menangkan calon pakatan harapan di segi besar   
2                   Norlelawati Sukiman amin pra   

                                                text  label split  \
0  Abi Ahmad Furqan memang Barisan Nasional dah l...      0  test   
1                          Ismail sabri dan muhiadin      0  test   
2                                        25k terbaik      0  test   

  dataset_source  
0       facebook  
1       facebook  
2       facebook

In [12]:
# initialize a list to store all the scores
scores = []
batch_size = 10

for n in tqdm(range(0, len(test_dataset), batch_size)):
    batch = []
    with torch.no_grad():
        for q, t in zip(test_dataset['query'][n: n + batch_size], test_dataset['text'][n: n + batch_size]):
            input_ids = tokenizer.encode_plus(q, t)
            input_ids.pop('token_type_ids')
            batch.append(input_ids)
        padded = tokenizer.pad(batch, return_tensors = 'pt').to('cuda')
        scores.extend(reranker_model(**padded).logits.cpu().detach().float().numpy().argmax(axis = 1).tolist())

  0%|          | 0/4500 [00:00<?, ?it/s]

In [13]:
# Evaluate predictions (macro)
true_labels = test_dataset["label"]
accuracy = accuracy_score(true_labels, scores)
roc_auc = roc_auc_score(true_labels, scores)
print("Accuracy:", accuracy)
print("ROC-AUC:", roc_auc)
print("\nClassification Report:")
print(classification_report(
    true_labels,
    scores,
    target_names=["class 0", "class 1"],
    digits=5
))
print("\nConfusion Matrix:")
print(confusion_matrix(true_labels, scores))

Accuracy: 0.9892222222222222
ROC-AUC: 0.9895004047687365

Classification Report:
              precision    recall  f1-score   support

     class 0    0.99408   0.98583   0.98994     24205
     class 1    0.98366   0.99317   0.98839     20795

    accuracy                        0.98922     45000
   macro avg    0.98887   0.98950   0.98917     45000
weighted avg    0.98927   0.98922   0.98923     45000


Confusion Matrix:
[[23862   343]
 [  142 20653]]


In [14]:
# save and export inferenced dataframe
inferenced_df = pd.concat([test_dataset, pd.DataFrame(scores, columns=['predicted_label'])], axis=1)
inferenced_df.head(3)

query  \
0                         Sekapur sirih road dah   
1  Menangkan calon pakatan harapan di segi besar   
2                   Norlelawati Sukiman amin pra   

                                                text  label split  \
0  Abi Ahmad Furqan memang Barisan Nasional dah l...      0  test   
1                          Ismail sabri dan muhiadin      0  test   
2                                        25k terbaik      0  test   

  dataset_source  predicted_label  
0       facebook                0  
1       facebook                0  
2       facebook                0

In [15]:
inferenced_df.to_json(
    f'inferenced_output/{model_used}-inferenced-{f_name}.jsonl',
    orient='records',
    lines=True
)

#### 3.0 Hansard QA

In [16]:
f = "test_datasets/test-reformatted-hansard-qa.jsonl"
f_name = f.split('reformatted-')[-1].split('.')[0]

test_dataset = pd.read_json(f, lines=True)
test_dataset['dataset_source'] = f_name

print('Shape:', test_dataset.shape)
test_dataset.head(3)

Shape: (12712, 5)


query  \
0    Siapakah wakil rakyat untuk kawasan Kota Belud?   
1  Berapa jumlah unit yang telah dibina oleh PR1M...   
2  Apakah langkah kerajaan yang hendak dikenakan ...   

                                                text  label split  \
0  \nii DR.07.12.2021 \n\n \n58. YB. Dr. Kelvin Y...      1  test   
1  from this seller User Review Submit A Review O...      0  test   
2  \n8                                           ...      1  test   

  dataset_source  
0     hansard-qa  
1     hansard-qa  
2     hansard-qa

In [17]:
# initialize a list to store all the scores
scores = []
batch_size = 10

for n in tqdm(range(0, len(test_dataset), batch_size)):
    batch = []
    with torch.no_grad():
        for q, t in zip(test_dataset['query'][n: n + batch_size], test_dataset['text'][n: n + batch_size]):
            input_ids = tokenizer.encode_plus(q, t)
            input_ids.pop('token_type_ids')
            batch.append(input_ids)
        padded = tokenizer.pad(batch, return_tensors = 'pt').to('cuda')
        scores.extend(reranker_model(**padded).logits.cpu().detach().float().numpy().argmax(axis = 1).tolist())

  0%|          | 0/1272 [00:00<?, ?it/s]

In [18]:
# Evaluate predictions (macro)
true_labels = test_dataset["label"]
accuracy = accuracy_score(true_labels, scores)
roc_auc = roc_auc_score(true_labels, scores)
print("Accuracy:", accuracy)
print("ROC-AUC:", roc_auc)
print("\nClassification Report:")
print(classification_report(
    true_labels,
    scores,
    target_names=["class 0", "class 1"],
    digits=5
))
print("\nConfusion Matrix:")
print(confusion_matrix(true_labels, scores))

Accuracy: 0.9911894273127754
ROC-AUC: 0.9911894273127753

Classification Report:
              precision    recall  f1-score   support

     class 0    0.99524   0.98710   0.99115      6356
     class 1    0.98720   0.99528   0.99123      6356

    accuracy                        0.99119     12712
   macro avg    0.99122   0.99119   0.99119     12712
weighted avg    0.99122   0.99119   0.99119     12712


Confusion Matrix:
[[6274   82]
 [  30 6326]]


In [19]:
# save and export inferenced dataframe
inferenced_df = pd.concat([test_dataset, pd.DataFrame(scores, columns=['predicted_label'])], axis=1)
inferenced_df.head(3)

query  \
0    Siapakah wakil rakyat untuk kawasan Kota Belud?   
1  Berapa jumlah unit yang telah dibina oleh PR1M...   
2  Apakah langkah kerajaan yang hendak dikenakan ...   

                                                text  label split  \
0  \nii DR.07.12.2021 \n\n \n58. YB. Dr. Kelvin Y...      1  test   
1  from this seller User Review Submit A Review O...      0  test   
2  \n8                                           ...      1  test   

  dataset_source  predicted_label  
0     hansard-qa                1  
1     hansard-qa                0  
2     hansard-qa                1

In [20]:
inferenced_df.to_json(
    f'inferenced_output/{model_used}-inferenced-{f_name}.jsonl',
    orient='records',
    lines=True
)

#### 4.0 IIUM Confession

In [21]:
f = "test_datasets/test-reformatted-iium-confession.jsonl"
f_name = f.split('reformatted-')[-1].split('.')[0]

test_dataset = pd.read_json(f, lines=True)
test_dataset['dataset_source'] = f_name

print('Shape:', test_dataset.shape)
test_dataset.head(3)

Shape: (45000, 5)


query  \
0  Means, dia berkurung dalam bilik, tarik muka d...   
1  Saya selalu follow seorang perunding imej feme...   
2  Dan aku juga kasihan akan diriku sendiri. Di r...   

                                                text  label split  \
0  "usia 20 an macam ni,memang kita perlukan sora...      0  test   
1  Aku sentiasa ikut seorang consultant image yan...      1  test   
2  And I also pity myself. In that house I was st...      1  test   

    dataset_source  
0  iium-confession  
1  iium-confession  
2  iium-confession

In [22]:
# initialize a list to store all the scores
scores = []
batch_size = 10

for n in tqdm(range(0, len(test_dataset), batch_size)):
    batch = []
    with torch.no_grad():
        for q, t in zip(test_dataset['query'][n: n + batch_size], test_dataset['text'][n: n + batch_size]):
            input_ids = tokenizer.encode_plus(q, t)
            input_ids.pop('token_type_ids')
            batch.append(input_ids)
        padded = tokenizer.pad(batch, return_tensors = 'pt').to('cuda')
        scores.extend(reranker_model(**padded).logits.cpu().detach().float().numpy().argmax(axis = 1).tolist())

  0%|          | 0/4500 [00:00<?, ?it/s]

In [23]:
# Evaluate predictions (macro)
true_labels = test_dataset["label"]
accuracy = accuracy_score(true_labels, scores)
roc_auc = roc_auc_score(true_labels, scores)
print("Accuracy:", accuracy)
print("ROC-AUC:", roc_auc)
print("\nClassification Report:")
print(classification_report(
    true_labels,
    scores,
    target_names=["class 0", "class 1"],
    digits=5
))
print("\nConfusion Matrix:")
print(confusion_matrix(true_labels, scores))

Accuracy: 0.9986888888888888
ROC-AUC: 0.9987423005524895

Classification Report:
              precision    recall  f1-score   support

     class 0    0.99734   0.99892   0.99813     15743
     class 1    0.99942   0.99856   0.99899     29257

    accuracy                        0.99869     45000
   macro avg    0.99838   0.99874   0.99856     45000
weighted avg    0.99869   0.99869   0.99869     45000


Confusion Matrix:
[[15726    17]
 [   42 29215]]


In [24]:
# save and export inferenced dataframe
inferenced_df = pd.concat([test_dataset, pd.DataFrame(scores, columns=['predicted_label'])], axis=1)
inferenced_df.head(3)

query  \
0  Means, dia berkurung dalam bilik, tarik muka d...   
1  Saya selalu follow seorang perunding imej feme...   
2  Dan aku juga kasihan akan diriku sendiri. Di r...   

                                                text  label split  \
0  "usia 20 an macam ni,memang kita perlukan sora...      0  test   
1  Aku sentiasa ikut seorang consultant image yan...      1  test   
2  And I also pity myself. In that house I was st...      1  test   

    dataset_source  predicted_label  
0  iium-confession                0  
1  iium-confession                1  
2  iium-confession                1

In [25]:
inferenced_df.to_json(
    f'inferenced_output/{model_used}-inferenced-{f_name}.jsonl',
    orient='records',
    lines=True
)

#### 5.0 B Cari

In [26]:
f = "test_datasets/test-reformatted-mining-b-cari-com-my.jsonl"
f_name = f.split('reformatted-')[-1].split('.')[0]

test_dataset = pd.read_json(f, lines=True)
test_dataset['dataset_source'] = f_name

print('Shape:', test_dataset.shape)
test_dataset.head(3)

Shape: (44910, 5)


query  \
0  Hello. I am a student. Every time I need to wr...   
1  betul ke boleh tapis? dan filter dalam tu mest...   
2  Jangan dia main campak masuk tong sampah bila ...   

                                                text  label split  \
0  Hello. Im a student. If I need to write an ess...      1  test   
1  Is it true that it can be filtered? And the fi...      1  test   
2                           mmmeeeeowwwwwwwwwwwwwwww      0  test   

         dataset_source  
0  mining-b-cari-com-my  
1  mining-b-cari-com-my  
2  mining-b-cari-com-my

In [27]:
# initialize a list to store all the scores
scores = []
batch_size = 10

for n in tqdm(range(0, len(test_dataset), batch_size)):
    batch = []
    with torch.no_grad():
        for q, t in zip(test_dataset['query'][n: n + batch_size], test_dataset['text'][n: n + batch_size]):
            input_ids = tokenizer.encode_plus(q, t)
            input_ids.pop('token_type_ids')
            batch.append(input_ids)
        padded = tokenizer.pad(batch, return_tensors = 'pt').to('cuda')
        scores.extend(reranker_model(**padded).logits.cpu().detach().float().numpy().argmax(axis = 1).tolist())

  0%|          | 0/4491 [00:00<?, ?it/s]

In [28]:
# Evaluate predictions (macro)
true_labels = test_dataset["label"]
accuracy = accuracy_score(true_labels, scores)
roc_auc = roc_auc_score(true_labels, scores)
print("Accuracy:", accuracy)
print("ROC-AUC:", roc_auc)
print("\nClassification Report:")
print(classification_report(
    true_labels,
    scores,
    target_names=["class 0", "class 1"],
    digits=5
))
print("\nConfusion Matrix:")
print(confusion_matrix(true_labels, scores))

Accuracy: 0.9942329102649744
ROC-AUC: 0.9942873584060126

Classification Report:
              precision    recall  f1-score   support

     class 0    0.99251   0.99496   0.99373     20642
     class 1    0.99571   0.99361   0.99466     24268

    accuracy                        0.99423     44910
   macro avg    0.99411   0.99429   0.99420     44910
weighted avg    0.99424   0.99423   0.99423     44910


Confusion Matrix:
[[20538   104]
 [  155 24113]]


In [29]:
# save and export inferenced dataframe
inferenced_df = pd.concat([test_dataset, pd.DataFrame(scores, columns=['predicted_label'])], axis=1)
inferenced_df.head(3)

query  \
0  Hello. I am a student. Every time I need to wr...   
1  betul ke boleh tapis? dan filter dalam tu mest...   
2  Jangan dia main campak masuk tong sampah bila ...   

                                                text  label split  \
0  Hello. Im a student. If I need to write an ess...      1  test   
1  Is it true that it can be filtered? And the fi...      1  test   
2                           mmmeeeeowwwwwwwwwwwwwwww      0  test   

         dataset_source  predicted_label  
0  mining-b-cari-com-my                1  
1  mining-b-cari-com-my                1  
2  mining-b-cari-com-my                0

In [30]:
inferenced_df.to_json(
    f'inferenced_output/{model_used}-inferenced-{f_name}.jsonl',
    orient='records',
    lines=True
)

#### 6.0 Summarization

In [47]:
f = "test_datasets/test-reformatted-mining-summarization.jsonl"
f_name = f.split('reformatted-')[-1].split('.')[0]

test_dataset = pd.read_json(f, lines=True)
test_dataset['dataset_source'] = f_name

print('Shape:', test_dataset.shape)
test_dataset.head(3)

Shape: (44123, 5)


query  \
0  Sektor pertanian dijangka pulih pada 2019 deng...   
1  Malaysia Today, a Malaysian news site, has bee...   
2  In the Malaysian General Election (GE15), no p...   

                                                text  label split  \
0  KUALA LUMPUR: Sektor pertanian dijangka pulih ...      1  test   
1  Tolong lah gais, aku nasihatkan tolong kunci p...      0  test   
2  PUTRAJAYA: Tiada mana-mana parti memperoleh 50...      1  test   

         dataset_source  
0  mining-summarization  
1  mining-summarization  
2  mining-summarization

In [48]:
# initialize a list to store all the scores
scores = []
batch_size = 2

for n in tqdm(range(0, len(test_dataset), batch_size)):
    batch = []
    with torch.no_grad():
        for q, t in zip(test_dataset['query'][n: n + batch_size], test_dataset['text'][n: n + batch_size]):
            input_ids = tokenizer.encode_plus(q, t)
            input_ids.pop('token_type_ids')
            batch.append(input_ids)
        padded = tokenizer.pad(batch, return_tensors = 'pt').to('cuda')
        scores.extend(reranker_model(**padded).logits.cpu().detach().float().numpy().argmax(axis = 1).tolist())

  0%|          | 0/22062 [00:00<?, ?it/s]

label
0    36614
1     7509
Name: count, dtype: int64

In [53]:
# Evaluate predictions (macro)
true_labels = test_dataset["label"]
accuracy = accuracy_score(true_labels, scores)
roc_auc = roc_auc_score(true_labels, scores)
print("Accuracy:", accuracy)
print("ROC-AUC:", roc_auc)
print("\nClassification Report:")
print(classification_report(
    true_labels,
    scores,
    target_names=["class 0", "class 1"],
    digits=5
))
print("\nConfusion Matrix:")
print(confusion_matrix(true_labels, scores))

Accuracy: 0.9968723794846225
ROC-AUC: 0.9921872271509471

Classification Report:
              precision    recall  f1-score   support

     class 0    0.99695   0.99929   0.99812     36614
     class 1    0.99650   0.98508   0.99076      7509

    accuracy                        0.99687     44123
   macro avg    0.99672   0.99219   0.99444     44123
weighted avg    0.99687   0.99687   0.99687     44123


Confusion Matrix:
[[36588    26]
 [  112  7397]]


In [50]:
# save and export inferenced dataframe
inferenced_df = pd.concat([test_dataset, pd.DataFrame(scores, columns=['predicted_label'])], axis=1)
inferenced_df.head(3)

In [51]:
inferenced_df.to_json(
    f'inferenced_output/{model_used}-inferenced-{f_name}.jsonl',
    orient='records',
    lines=True
)

#### 7.0 News

In [42]:
f = "test_datasets/test-reformatted-news.jsonl"
f_name = f.split('reformatted-')[-1].split('.')[0]

test_dataset = pd.read_json(f, lines=True)
test_dataset['dataset_source'] = f_name

print('Shape:', test_dataset.shape)
test_dataset.head(3)

Shape: (45000, 5)


query  \
0  Bridgerton: sex, gossip and race in Regency Lo...   
1     PAS minta putus dengan PKR kerana Selena Gomez   
2                 Harga MSM dijangka terus meningkat   

                                                text  label split  \
0  THE appointment of Najib Razak as chairman of ...      0  test   
1  \n(Focus Malaysia) – Legal practitioner Khairu...      0  test   
2   LONDON, Feb 9 — Lewis Hamilton has signed a o...      0  test   

  dataset_source  
0           news  
1           news  
2           news

In [43]:
# initialize a list to store all the scores
scores = []
batch_size = 5

for n in tqdm(range(0, len(test_dataset), batch_size)):
    batch = []
    with torch.no_grad():
        for q, t in zip(test_dataset['query'][n: n + batch_size], test_dataset['text'][n: n + batch_size]):
            input_ids = tokenizer.encode_plus(q, t)
            input_ids.pop('token_type_ids')
            batch.append(input_ids)
        padded = tokenizer.pad(batch, return_tensors = 'pt').to('cuda')
        scores.extend(reranker_model(**padded).logits.cpu().detach().float().numpy().argmax(axis = 1).tolist())

  0%|          | 0/9000 [00:00<?, ?it/s]

In [44]:
# Evaluate predictions (macro)
true_labels = test_dataset["label"]
accuracy = accuracy_score(true_labels, scores)
roc_auc = roc_auc_score(true_labels, scores)
print("Accuracy:", accuracy)
print("ROC-AUC:", roc_auc)
print("\nClassification Report:")
print(classification_report(
    true_labels,
    scores,
    target_names=["class 0", "class 1"],
    digits=5
))
print("\nConfusion Matrix:")
print(confusion_matrix(true_labels, scores))

Accuracy: 0.9939111111111111
ROC-AUC: 0.9861437536507428

Classification Report:
              precision    recall  f1-score   support

     class 0    0.99486   0.99784   0.99635     37446
     class 1    0.98912   0.97445   0.98173      7554

    accuracy                        0.99391     45000
   macro avg    0.99199   0.98614   0.98904     45000
weighted avg    0.99390   0.99391   0.99389     45000


Confusion Matrix:
[[37365    81]
 [  193  7361]]


In [45]:
# save and export inferenced dataframe
inferenced_df = pd.concat([test_dataset, pd.DataFrame(scores, columns=['predicted_label'])], axis=1)
inferenced_df.head(3)

query  \
0  Bridgerton: sex, gossip and race in Regency Lo...   
1     PAS minta putus dengan PKR kerana Selena Gomez   
2                 Harga MSM dijangka terus meningkat   

                                                text  label split  \
0  THE appointment of Najib Razak as chairman of ...      0  test   
1  \n(Focus Malaysia) – Legal practitioner Khairu...      0  test   
2   LONDON, Feb 9 — Lewis Hamilton has signed a o...      0  test   

  dataset_source  predicted_label  
0           news                0  
1           news                0  
2           news                0

In [46]:
inferenced_df.to_json(
    f'inferenced_output/{model_used}-inferenced-{f_name}.jsonl',
    orient='records',
    lines=True
)

#### 8.0 Twitter

In [31]:
f = "test_datasets/test-reformatted-twitter.jsonl"
f_name = f.split('reformatted-')[-1].split('.')[0]

test_dataset = pd.read_json(f, lines=True)
test_dataset['dataset_source'] = f_name

print('Shape:', test_dataset.shape)
test_dataset.head(3)

Shape: (45000, 5)


query  \
0         @nickgle_ Sugarbun tapi nadai manuk tadi.    
1  Semua laki laki sama aja.\nTapi kalo kamu sama...   
2  11:16am PLUS@E1 :  Kerja penyelenggaraan KM 23...   

                                                text  label split  \
0                @nickgle_ Sugarbun tapi xda ayam td      1  test   
1       @hardliffee Jngan terlalu larut tidurnya yaa      0  test   
2  Maintenance work KM 231.0 - KM 233.0 South fro...      1  test   

  dataset_source  
0        twitter  
1        twitter  
2        twitter

In [32]:
# initialize a list to store all the scores
scores = []
batch_size = 10

for n in tqdm(range(0, len(test_dataset), batch_size)):
    batch = []
    with torch.no_grad():
        for q, t in zip(test_dataset['query'][n: n + batch_size], test_dataset['text'][n: n + batch_size]):
            input_ids = tokenizer.encode_plus(q, t)
            input_ids.pop('token_type_ids')
            batch.append(input_ids)
        padded = tokenizer.pad(batch, return_tensors = 'pt').to('cuda')
        scores.extend(reranker_model(**padded).logits.cpu().detach().float().numpy().argmax(axis = 1).tolist())

  0%|          | 0/4500 [00:00<?, ?it/s]

In [33]:
# Evaluate predictions (macro)
true_labels = test_dataset["label"]
accuracy = accuracy_score(true_labels, scores)
roc_auc = roc_auc_score(true_labels, scores)
print("Accuracy:", accuracy)
print("ROC-AUC:", roc_auc)
print("\nClassification Report:")
print(classification_report(
    true_labels,
    scores,
    target_names=["class 0", "class 1"],
    digits=5
))
print("\nConfusion Matrix:")
print(confusion_matrix(true_labels, scores))

Accuracy: 0.9966444444444444
ROC-AUC: 0.9965723169940125

Classification Report:
              precision    recall  f1-score   support

     class 0    0.99595   0.99611   0.99603     19010
     class 1    0.99715   0.99704   0.99709     25990

    accuracy                        0.99664     45000
   macro avg    0.99655   0.99657   0.99656     45000
weighted avg    0.99664   0.99664   0.99664     45000


Confusion Matrix:
[[18936    74]
 [   77 25913]]


In [34]:
# save and export inferenced dataframe
inferenced_df = pd.concat([test_dataset, pd.DataFrame(scores, columns=['predicted_label'])], axis=1)
inferenced_df.head(3)

query  \
0         @nickgle_ Sugarbun tapi nadai manuk tadi.    
1  Semua laki laki sama aja.\nTapi kalo kamu sama...   
2  11:16am PLUS@E1 :  Kerja penyelenggaraan KM 23...   

                                                text  label split  \
0                @nickgle_ Sugarbun tapi xda ayam td      1  test   
1       @hardliffee Jngan terlalu larut tidurnya yaa      0  test   
2  Maintenance work KM 231.0 - KM 233.0 South fro...      1  test   

  dataset_source  predicted_label  
0        twitter                1  
1        twitter                0  
2        twitter                1

In [35]:
inferenced_df.to_json(
    f'inferenced_output/{model_used}-inferenced-{f_name}.jsonl',
    orient='records',
    lines=True
)

#### 9.0 Wikipedia QA

In [36]:
f = "test_datasets/test-reformatted-wikipedia-qa.jsonl"
f_name = f.split('reformatted-')[-1].split('.')[0]

test_dataset = pd.read_json(f, lines=True)
test_dataset['dataset_source'] = f_name

print('Shape:', test_dataset.shape)
test_dataset.head(3)

Shape: (32903, 5)


query  \
0      Apakah penyakit yang diderita oleh Sharielda?   
1  Siapakah komposer muda yang Chrisye dekati unt...   
2  Siapakah yang menfailkan petisyen untuk menunt...   

                                                text  label split  \
0  \nDR. 26.7.2022 103 \n\n \nkemungkinan daripad...      0  test   
1  Guruh, dan beliau juga akan berjumpa dengannya...      1  test   
2  \n56   DR. 10.7.2019 \n\n \n\n \n\nTuan Yang d...      0  test   

  dataset_source  
0   wikipedia-qa  
1   wikipedia-qa  
2   wikipedia-qa

In [37]:
# initialize a list to store all the scores
scores = []
batch_size = 10

for n in tqdm(range(0, len(test_dataset), batch_size)):
    batch = []
    with torch.no_grad():
        for q, t in zip(test_dataset['query'][n: n + batch_size], test_dataset['text'][n: n + batch_size]):
            input_ids = tokenizer.encode_plus(q, t)
            input_ids.pop('token_type_ids')
            batch.append(input_ids)
        padded = tokenizer.pad(batch, return_tensors = 'pt').to('cuda')
        scores.extend(reranker_model(**padded).logits.cpu().detach().float().numpy().argmax(axis = 1).tolist())

  0%|          | 0/3291 [00:00<?, ?it/s]

In [38]:
# save and export inferenced dataframe
inferenced_df = pd.concat([test_dataset, pd.DataFrame(scores, columns=['predicted_label'])], axis=1)
inferenced_df.head(3)

query  \
0      Apakah penyakit yang diderita oleh Sharielda?   
1  Siapakah komposer muda yang Chrisye dekati unt...   
2  Siapakah yang menfailkan petisyen untuk menunt...   

                                                text  label split  \
0  \nDR. 26.7.2022 103 \n\n \nkemungkinan daripad...      0  test   
1  Guruh, dan beliau juga akan berjumpa dengannya...      1  test   
2  \n56   DR. 10.7.2019 \n\n \n\n \n\nTuan Yang d...      0  test   

  dataset_source  predicted_label  
0   wikipedia-qa                0  
1   wikipedia-qa                1  
2   wikipedia-qa                0

In [39]:
inferenced_df.to_json(
    f'inferenced_output/{model_used}-inferenced-{f_name}.jsonl',
    orient='records',
    lines=True
)

In [40]:
f = "test_datasets/test-reformatted-wikipedia-qa.jsonl"
f_name = f.split('reformatted-')[-1].split('.')[0]
test_dataset = pd.read_json(f"inferenced_output/{model_used}-inferenced-{f_name}.jsonl", lines=True, orient='records')
scores = test_dataset["predicted_label"]

test_dataset["label"].value_counts()

label
0    16452
1    16451
Name: count, dtype: int64

In [41]:
# Evaluate predictions (macro)
true_labels = test_dataset["label"]
accuracy = accuracy_score(true_labels, scores)
roc_auc = roc_auc_score(true_labels, scores)
print("Accuracy:", accuracy)
print("ROC-AUC:", roc_auc)
print("\nClassification Report:")
print(classification_report(
    true_labels,
    scores,
    target_names=["class 0", "class 1"],
    digits=5
))
print("\nConfusion Matrix:")
print(confusion_matrix(true_labels, scores))

Accuracy: 0.9980852809774184
ROC-AUC: 0.998085287441521

Classification Report:
              precision    recall  f1-score   support

     class 0    0.99830   0.99787   0.99808     16452
     class 1    0.99787   0.99830   0.99809     16451

    accuracy                        0.99809     32903
   macro avg    0.99809   0.99809   0.99809     32903
weighted avg    0.99809   0.99809   0.99809     32903


Confusion Matrix:
[[16417    35]
 [   28 16423]]
